# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: start report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 1-5'

concurrency:
  group: ${{ github.workflow }}
 
permissions:
  contents: read

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: notification
        run: |
          curl "https://linebot.school.donaishitanyarobert.mydns.jp/report"
